# Generated by Django 4.1.5 on 2023-01-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tv_view", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubMeta",
            fields=[
                ("club", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=30)),
                ("way_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("game", models.AutoField(primary_key=True, serialize=False)),
                ("game_name", models.CharField(max_length=30)),
                ("game_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Ligue",
            fields=[
                ("lugue", models.AutoField(primary_key=True, serialize=False)),
                ("ligue_name", models.CharField(max_length=30)),
                (
                    "club_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tv_view.clubmeta",
                    ),
                ),
            ],
        ),
    ]
