# Generated by Django 4.1.5 on 2023-01-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tv_view", "0002_clubmeta_game_ligue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ligue",
            old_name="lugue",
            new_name="ligue",
        ),
    ]
