# Generated by Django 4.1.5 on 2023-01-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tv_view", "0003_rename_lugue_ligue_ligue"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmeta",
            name="club_name",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name="command",
            name="game_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="tv_view.game",
            ),
        ),
        migrations.AddField(
            model_name="command",
            name="lugue_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="tv_view.ligue",
            ),
        ),
    ]
