# Generated by Django 4.1.5 on 2023-01-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tv_view", "0004_clubmeta_club_name_command_game_id_command_lugue_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clubmeta",
            name="club_name",
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
